2019-12-17 14:19:00,606 ERROR: Exception on /explore [GET] [in c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\duvolle\Desktop\microblog\app\routes.py", line 50, in explore
    next_url=next_url, prev_url=prev_url)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\duvolle\Desktop\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\duvolle\Desktop\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\duvolle\Desktop\microblog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\duvolle\Desktop\microblog\app\templates\index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "C:\Users\duvolle\Desktop\microblog\app\templates\_post.html", line 12, in top-level template code
    said {{ moment(post.timestamp).fromNow('LLL') }}:
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_moment.py", line 133, in fromNow
    return self._render("fromNow(%s)" % int(no_suffix), refresh)
ValueError: invalid literal for int() with base 10: 'LLL'
2019-12-17 14:19:02,374 ERROR: Exception on /index [GET] [in c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\duvolle\Desktop\microblog\app\routes.py", line 37, in index
    prev_url=prev_url)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\duvolle\Desktop\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\duvolle\Desktop\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\duvolle\Desktop\microblog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\duvolle\Desktop\microblog\app\templates\index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "C:\Users\duvolle\Desktop\microblog\app\templates\_post.html", line 12, in top-level template code
    said {{ moment(post.timestamp).fromNow('LLL') }}:
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_moment.py", line 133, in fromNow
    return self._render("fromNow(%s)" % int(no_suffix), refresh)
ValueError: invalid literal for int() with base 10: 'LLL'
2019-12-17 14:19:34,006 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:49]
2019-12-17 14:19:39,709 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:49]
2019-12-17 14:20:30,094 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:49]
2019-12-17 14:23:15,751 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:49]
2019-12-17 14:23:31,920 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:49]
