2019-12-20 11:47:45,478 ERROR: Exception on /index [GET] [in c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\duvolle\Desktop\microblog\app\routes.py", line 38, in index
    prev_url=prev_url)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\duvolle\Desktop\microblog\app\templates\index.html", line 5, in template
    <h1>{{ _('Hey, %(username)s!' , username=current_user.username)</h1>
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 620, in parse_tuple
    args.append(parse())
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 450, in parse_or
    left = self.parse_and()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 459, in parse_and
    left = self.parse_not()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 470, in parse_not
    return self.parse_compare()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 480, in parse_compare
    ops.append(nodes.Operand(token_type, self.parse_math1()))
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 583, in parse_primary
    self.fail("unexpected '%s'" % describe_token(token), token.lineno)
  File "c:\users\duvolle\downloads\opendatascience\ods\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: unexpected '/'
2019-12-20 12:21:03,822 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:52]
2019-12-21 11:30:46,736 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:52]
2019-12-21 11:51:57,865 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:52]
2019-12-21 12:04:31,739 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:52]
2019-12-21 12:13:56,425 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:52]
2019-12-21 12:15:09,927 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:52]
2019-12-21 12:18:46,066 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:52]
2019-12-21 12:45:37,683 INFO: Microblog startup [in C:\Users\duvolle\Desktop\microblog\app\__init__.py:52]
